# Generated by Django 3.1.2 on 2020-10-12 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [  # type: ignore
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('bot_type', models.PositiveSmallIntegerField(choices=[(10, 'Type_jivosite'), (11, 'Type_ok')],
                                                              verbose_name='Bot Type')),  # noqa: E501
            ],
            options={
                'verbose_name': 'Bot',
                'verbose_name_plural': 'Bots',
                'ordering': ['bot_type'],
            },
        ),
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('messenger_user_id', models.CharField(max_length=64, verbose_name='MessengerUserId')),
                ('messenger_user_url',
                 models.URLField(blank=True, max_length=2047, null=True, verbose_name='MessengerUserURL')),
                # noqa: E501
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('avatar_url', models.URLField(blank=True, max_length=2047, null=True, verbose_name='Avatar')),
                ('lang_code',
                 models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('fr', 'French'), ('uz', "O'zbek")],
                                  max_length=2, verbose_name='User language')),  # noqa: E501
                ('bot',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.bot', verbose_name='Bot')),
                # noqa: E501
            ],
            options={
                'verbose_name': 'Bot user',
                'verbose_name_plural': 'BotUsers',
                'ordering': ['bot', '-created_at'],
                'unique_together': {('bot', 'messenger_user_id')},
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Private'), (2, 'Group'), (3, 'Channel')],
                                                          verbose_name='Type')),  # noqa: E501
                ('id_in_messenger', models.CharField(max_length=64, verbose_name='Id in messenger')),
                ('url_in_messenger',
                 models.URLField(blank=True, max_length=2047, null=True, verbose_name='URLInMessenger')),  # noqa: E501
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('avatar_url', models.URLField(blank=True, max_length=2047, null=True, verbose_name='Avatar')),
                ('last_message_time', models.DateTimeField(blank=True, null=True)),
                ('last_message_text', models.CharField(blank=True, max_length=100, null=True)),
                ('bot',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.bot', verbose_name='Bot')),
                # noqa: E501
                ('bot_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                  to='bot.botuser', verbose_name='BotUser')),  # noqa: E501
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chats',
                'ordering': ('-last_message_time', 'bot'),
                'unique_together': {('bot', 'id_in_messenger')},
                'index_together': {('bot', 'id_in_messenger')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('status', models.PositiveSmallIntegerField(
                    choices=[(1, 'New'), (3, 'Sent'), (5, 'Failed'), (10, 'Delivered'), (13, 'Read'), (15, 'Deleted')],
                    default=1, verbose_name='Status')),  # noqa: E501
                ('direction', models.PositiveSmallIntegerField(choices=[(1, 'Received'), (2, 'Sent'), (3, 'System')],
                                                               verbose_name='Direction')),  # noqa: E501
                ('content_type', models.PositiveSmallIntegerField(
                    choices=[(1, 'Text'), (2, 'Image'), (3, 'Contact'), (4, 'Voice'), (5, 'Remove'), (6, 'Command'),
                             (7, 'System'), (8, 'File'), (9, 'Inline')], verbose_name='Content type')),  # noqa: E501
                ('id_in_messenger',
                 models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='ID in messenger')),
                # noqa: E501
                ('reply_id_in_messenger', models.CharField(blank=True, db_index=True, max_length=64, null=True,
                                                           verbose_name='Reply ID in messenger')),  # noqa: E501
                ('ts_in_messenger', models.DateTimeField(blank=True, null=True, verbose_name='Timestamp in messenger')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('image_url', models.URLField(blank=True, max_length=2047, null=True, verbose_name='Image')),
                ('file_url', models.URLField(blank=True, max_length=2047, null=True, verbose_name='File')),
                ('video_url', models.URLField(blank=True, max_length=2047, null=True, verbose_name='Video')),
                ('language', models.CharField(default='ru', max_length=11, verbose_name='Language code')),
                ('bot',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.bot', verbose_name='Bot')),
                # noqa: E501
                ('bot_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                               to='bot.botuser', verbose_name='Bot user')),  # noqa: E501
                ('chat',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.chat',
                                   verbose_name='Chat')),  # noqa: E501
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-created_at', 'bot', 'bot_user'],
            },
        ),
    ]
