name: Test runner

on:
  pull_request:
    branches:
      - '*'
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Python installation
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install virtualenv
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run:  |
          pip install -r requirements.txt

      - name: MakeMigrations
        run: |
          python manage.py makemigrations

      - name: Run pytest
        run: pytest -q